name: Clear Jupyter Notebook Outputs

on:
  push:
    branches:
      - "!main"
  pull_request:

jobs:
  clear_notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install nbstripout
      run: pip install nbstripout

    - name: Clear Jupyter notebook outputs
      id: verify_diff
      run: |
        nbstripout main.ipynb
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Push changes
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config --global --add safe.directory /github/workspace
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Clear notebook outputs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
